### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by Splitix** [Splitix/hammer#1]
Working on the login page and getting that to connect to a DB stored on the server.

**Comment by Preheat** [comment]
+1

**Comment by Splitix** [comment]
Implemented the login/registration form. 

Still needing to implement the JS and API call to the mongoDB to make it work.

**Comment by bab178** [comment]
Added corresponding form to match the DB.

**Comment by bab178** [comment]
Still need angular verification that the two passwords match on Sign up.
I don't know how you want email, image, and the other fields to be added, if you add them as it is it overflows.

**Comment by Splitix** [comment]
This seems to be working. Closing Issue.
