### ISSUE TITLE
Login - Alerts

### ISSUE THREAD

**Issue by Splitix** [Splitix/hammer#10]
During signup alert the user if:
-Password is Less than 6 characters
-Username is taken
-Passwords don't match

During Login alert the user if:
-Login/Password failed
*Note do not tell the user which field failed. Just says that either username or password was incorrect.

**Comment by Preheat** [comment]
server.js
-Status 500 indicates bad username, 501 for bad password.
-Error text changed to not disclose whether the username or password is the issue: 'Username or password combination was incorrect.'

controllers.js
-alerts added for signIn and signUp
